### ISSUE TITLE
Access-Control-Allow-Origin causing Cross-Origin errors

### ISSUE THREAD

**Issue by GGG-KILLER** [Domination9987/KissAnime-Cartoon-Downloader#10]
As I tried to solve with my pull request (#9) but failed because of browser security, the lack of a `Access-Control-Allow-Origin` header on the kissanime website (and probably the rest of their websites) causes iframe communication through `postMessage` and internal HTTP requests through `XMLHttpRequest` impossible.

I tried to solve the issue with the `XMLHttpRequest` by making the script use `GM_xmlhttpRequest` and `<script>` tags instead but it didn't fix the script entirely because of the `window.parent.postMessage({origin:host, class:'captcha'}, host);` that is used to communicate between the frames and the main window.

I'm using Chrome 51.0.2704.106 x64.

**Comment by Domination9987** [comment]
That seems strange, I thought `Access-Control-Allow-Origin` was thrown only if the page was being requested from a different domain, but apparently not it seems...

I guess if the only problem you're having is `postMessage` after substituting  `GM_xmlhttpRequest` for the `GET` requests, you could replace it with `GM_setValue` and `GM_getValue`, which allow for variables to be set across domains. Take care that you can't use objects, so you'd probably have to use `JSON.stringify` and `JSON.parse`, as per [documentation](https://wiki.greasespot.net/GM_setValue):

> function GM_setValue( name, value )
**Arguments**
`name`
`String` The unique (within this script) name for this value. Should be restricted to valid Javascript identifier characters.
`value`
`String`, `Integer` or `Boolean` Any valid value of these types. Any other type may cause undefined behavior, including crashes.

The other problem that may show up is that some variables are accessed from inner frames, including `processes` and the `DOM`, and it would be quite a messy solution.

I suppose the script could be rewritten to rely exclusively on `GM_xmlhttpRequest` for fetching the page data and the decoding script/s, and then using `GM_download` to start the download with the correct name (which may or may not work).

Anyway I can't reproduce this problem, it seems to be working fine on v51.0.2704.103 (64-bit)

**Comment by GGG-KILLER** [comment]
I found the problem.

Apparently the chrome extension [Https Everywhere](https://www.eff.org/https-everywhere) has 
KissAnime.to on it's list and by redirecting every page to the https:// version, the `Access-Control-Allow-Origin` no longer existed thus breaking the script. After disabling the extension on kissanime the script started to work again.
