### ISSUE TITLE
JDownloader - mixed content

### ISSUE THREAD

**Issue by nathanprocks** [Domination9987/KissAnime-Cartoon-Downloader#2]
The switch to HTTPS broke the "Download with JDownloader" setting.
>Mixed Content: The page at 'https://kissanime.to/Anime/Fairy-Tail-Dub' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://127.0.0.1:9666/flashgot'. This request has been blocked; the content must be served over HTTPS.

Iframes won't work for this. A form element will work, but results in a blank tab when the form is submitted. Submitting the form in an iframe results in error.

**Comment by Domination9987** [comment]
You are correct in that a new window would solve this problem...

However I don't really want to make a new window if it all possible.

I'm currently looking for an HTTPS alternative for the flashgot interface or some way to load the HTTP interface within the window (although I really don't think there is)

**Comment by nathanprocks** [comment]
Allowing insecure content for the page works temporarily. Not a good solution though.

I'm still have the other issue, so I still can't download at all with this userscript. When I click download, JDownloader asks me if I want to allow an external application to add links. I click yes and nothing is added. Then the iframeCheck error pops up.

**Comment by Domination9987** [comment]
>  I click yes and nothing is added
This was most likely related to an improper link being send to JDownloader. Please retry in 0.47

**Comment by nathanprocks** [comment]
It works in 0.47. I still have the problems mentioned in the other issue when downloading with JDownloader.

**Comment by Domination9987** [comment]
Yeah sending links to JDownloader is problematic because it is insecure content. I'm looking into a small Java or Flash applet that might be able to make insecure requests (even when embedded on a secure site)

**Comment by nathanprocks** [comment]
Please do not use Java because NPAPI plugins are not supported in Chrome as of version 45.

**Comment by Domination9987** [comment]
Would using something like [this](http://www.webwasp.co.uk/tutorials/b20-send-info-js/index.php) be useful would you say?

I'm thinking of sending the information required for the POST request to JDownload to the flash object, and then having the flash object perform an insecure POST request. Is that a feasible solution (flash doesn't use NPAPI right?)

**Comment by nathanprocks** [comment]
That should work. Chrome has it's own PPAPI Flash player.

**Comment by Domination9987** [comment]
Update: Chrome has an experimental flag that can be used that allows HTTPS requests to be made to JDownload's flashgot interface.

Found at chrome://flags
![Image](http://puu.sh/mLuYR/a51c26a99d.png)

**Comment by nathanprocks** [comment]
I noticed the commit a few days ago. I already found and enabled the flag.
Thank you for finding a solution for Chrome! :D

I just found a solution for Firefox:

1. Go to Preferences > Advanced > View Certificates > Servers > Add Exception...
2. Location: https://127.0.0.1:9666
3. Get Certificate (JDownloader must open or this will not work)
4. Confirm Security Exception
5. OK

**Comment by Domination9987** [comment]
Wow, nice find ;)

Good to see JDownloader back in business.
