### ISSUE TITLE
not an issue but a sugestion

### ISSUE THREAD

**Issue by sethnine** [Domination9987/KissAnime-Cartoon-Downloader#8]
can you make it so in the settings there is a way to only download a few files at once so people don't download 40 episodes at once and all the downloads time out

**Comment by Domination9987** [comment]
You can use the "Download Delay" slider in settings to set a waiting period of up to 5 seconds between each download... is this what you're looking for?

**Comment by sethnine** [comment]
no but i can do what i wanted to do witch j downloader and your plugin under jdownloader 2/ settings/general/max. simultaneous downloads so you already kind of did it
